### ISSUE TITLE
Not showing dots

### ISSUE THREAD

**Issue by faziltm** [celerysoft/ImagePager#1]
![screenshot_2017-01-14-10-51-46](https://cloud.githubusercontent.com/assets/16598628/21952638/82692188-da48-11e6-84eb-54a4e5dd0f9a.png)

It is showing number in sliding. But preview image it shows dots. How to add dots on it. And also i want to change the position of sliding numbers (The numbers showing instead of dots). How it possible? Please help me?

**Comment by celerysoft** [comment]
Commit 1c932daa9f5320d86e625c8779d3cc8844dbae66 contain a dot-indicator. I forgot to push it to GitHub, sorry about this.
