### ISSUE TITLE
Slace type for Images

### ISSUE THREAD

**Issue by lblfantasy** [celerysoft/ImagePager#2]
IS there any way to Scale the images to fitCenter for exemple, Because my imagePager is 200 dp in height and not full screen or match parent and image is not scaling properly.

**Comment by celerysoft** [comment]
Hi, i decide to add a method in `SimpleImagePagerAdapter` next update.

if u need in a hurry, u can change the code in `SimpleImagePagerAdapter`, modify the `getItem(int position)` method, set a ScaleType for the PhotoView instance.
