### ISSUE TITLE
How to start slider with a specific index?

### ISSUE THREAD

**Issue by AlaaZarifa** [celerysoft/ImagePager#3]
I'd like once the activity opens =>  the sliders shows the image with index 4 for example from the list!?
keeping in mind, the indicators and swipes are update with the index, so I swipe to the right or left it will show image with index 3 or 5 and so on..!
Any way to accomplish this?

Thanks for this awesome library!

**Comment by celerysoft** [comment]
Hi, u can use the `moveToImage()` method like this:

```
private ImagePager mImagePager;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    setContentView(R.layout.activity_main);

    mImagePager = findViewById(R.id.main_image_pager);
    mImagePager.moveToImage(4);
}
```

Hope this could help u:D

**Comment by AlaaZarifa** [comment]
Thanks a lot, works like a charm 👍
