### ISSUE TITLE
I hope the loading screen will change.

### ISSUE THREAD

**Issue by SeokHoBu** [celerysoft/ImagePager#4]
I hope the loading screen will change.
It would be nice if basic progress were used.
I am worried because the current loading picture does not fit the design of my phone. I would appreciate it very much if you could replace it.
Other features seem to be much better than other libraries.

Thank you!

**Comment by celerysoft** [comment]
Now you can use your own placeholder image by below codes:

```
private ImagePager mImagePager;

mImagePager = findViewById(R.id.main_image_pager);
mImagePager.setPlaceholder(R.drawable.placeholder);
```

Sorry for the late update.
