### ISSUE TITLE
How to change background color?

### ISSUE THREAD

**Issue by SPSpisoft** [celerysoft/ImagePager#5]
Hi..
Can I change background color from BLACK to another color ?

Tank's

**Comment by celerysoft** [comment]
```
ImagePager mImagePager;
mImagePager.setBackgroundColor(Color.parseColor("#FFFFFF"));
```

However, you may need to implement the `Indicator` on your own.

`TextIndicator` and `DotIndicator` are build-in `Indicator`

**Comment by SPSpisoft** [comment]
Thank you, it worked :)
